name: spotly
description: Aplicación de turismo disruptiva para Bolivia.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # 🌐 CORE
  supabase_flutter: ^2.12.0
  flutter_dotenv: ^6.0.0

  # 🏛️ ARCHITECTURE
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7
  dartz: ^0.10.1
  get_it: ^7.7.0

  # 🎨 UI & DESIGN SYSTEM
  flex_color_scheme: ^7.3.1
  google_fonts: ^6.2.1
  lucide_icons: ^0.257.0  # Versión estable para evitar errores de nombres
  font_awesome_flutter: ^10.7.0
  flutter_animate: ^4.5.0
  rive: ^0.13.0
  glass_kit: 4.0.2
  flutter_custom_clippers: ^2.1.0
  
  # 🖼️ MEDIA
  cached_network_image: ^3.3.1
  image_picker: ^1.1.0
  path: ^1.9.0

  # 🧭 NAVIGATION & MAPS
  go_router: ^13.2.0
  google_maps_flutter: ^2.6.1
  geolocator: ^14.0.1
  geocoding: ^3.0.0
  latlong2: ^0.9.1
  flutter_map: ^6.1.0

  # ⚙️ UTILS
  intl: ^0.19.0
  url_launcher: ^6.2.5
  share_plus: 12.0.2

dependency_overrides:
  win32: ^5.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  timeago: ^3.6.1
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true

  # 📁 RECURSOS
  assets:
    - .env
   # - assets/images/
   # - assets/rive/

  # 🖋️ FUENTES (Usando Google Fonts via paquete, no necesitas declararlas aquí)
flutter_launcher_icons:
  android: true
  image_path: "assets/icon/SpotlyIcon.png"